version: '3.9'

services:
    php:
        container_name: advanced_project_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    nginx:
        container_name: advanced_project_nginx
        image: nginx:stable-alpine
        volumes:
            - .:/var/www/html
            - /var/www/html/var
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - php

    db:
        container_name: advanced_project_db
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        container_name: advanced_project_redis
        image: redis:alpine
        ports:
            - "6379:6379"

    rabbitmq:
        container_name: advanced_project_rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15672:15672" # UI
            - "5672:5672"   # AMQP

volumes:
    pgdata:
